"""Simulator tools for AI character preview image generation.

Uses Gemini native image generation to create makeup preview illustrations
and uploads them to Cloud Storage.
"""

import logging
import os
from typing import Any

from google import genai
from google.cloud import firestore, storage
from google.genai import types

from ..prompts.simulator import build_image_prompt, DEFAULT_THEME

logger = logging.getLogger(__name__)

_storage_client: storage.Client | None = None
_firestore_db: firestore.Client | None = None


def _get_storage() -> storage.Client:
    global _storage_client
    if _storage_client is None:
        _storage_client = storage.Client()
    return _storage_client


def _get_firestore() -> firestore.Client:
    global _firestore_db
    if _firestore_db is None:
        _firestore_db = firestore.Client()
    return _firestore_db


async def generate_preview_image(
    recipe_id: str,
    user_id: str,
    steps: list[dict],
    theme: str = DEFAULT_THEME,
) -> dict[str, Any]:
    """Generate a preview image for a makeup recipe using Gemini image generation.

    This is called directly from server.py (not as an ADK tool) after a recipe
    is saved. It generates an illustration, uploads to GCS, and updates Firestore.

    Args:
        recipe_id: Firestore document ID of the saved recipe.
        user_id: User ID for storage path and Firestore update.
        steps: Recipe steps from the Alchemist agent output.
        theme: Character theme ('cute', 'cool', 'elegant').

    Returns:
        Dict with 'status', 'image_url', and optionally 'error'.
    """
    bucket_name = os.environ.get("GCS_PREVIEW_BUCKET", "alcheme-previews")
    model_name = os.environ.get("SIMULATOR_MODEL", "gemini-2.0-flash-exp")

    try:
        # Build the image generation prompt
        prompt = build_image_prompt(steps, theme)
        logger.info("Generating preview image for recipe %s (theme=%s)", recipe_id, theme)

        # Call Gemini with image generation
        client = genai.Client()
        response = await client.aio.models.generate_content(
            model=model_name,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE", "TEXT"],
            ),
        )

        # Extract image from response
        image_data: bytes | None = None
        if response.candidates:
            for part in response.candidates[0].content.parts:
                if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                    image_data = part.inline_data.data
                    break

        if not image_data:
            return {"status": "error", "error": "No image generated by model"}

        # Upload to Cloud Storage
        blob_path = f"{user_id}/{recipe_id}.webp"
        bucket = _get_storage().bucket(bucket_name)
        blob = bucket.blob(blob_path)
        blob.upload_from_string(image_data, content_type="image/webp")
        blob.make_public()
        image_url = blob.public_url

        # Update Firestore recipe document with preview image URL
        _get_firestore().collection("users").document(user_id).collection(
            "recipes"
        ).document(recipe_id).update(
            {
                "preview_image_url": image_url,
                "character_theme": theme,
            }
        )

        logger.info("Preview image saved: %s", image_url)
        return {"status": "success", "image_url": image_url}

    except Exception as e:
        logger.error("Preview image generation failed for recipe %s: %s", recipe_id, e, exc_info=True)
        return {"status": "error", "error": str(e)}
